// Business Unit data from the provided CSV file
export interface BusinessUnit {
  description: string;
  businessUnit: string;
}

export const businessUnits: BusinessUnit[] = [
  { description: "Agriculture Department", businessUnit: "B0401" },
  { description: "Agriculture Dept - US Bank", businessUnit: "B0402" },
  { description: "Office of Cannabis Management", businessUnit: "B1001" },
  { description: "Cosmetologist Examiners Board", businessUnit: "B1101" },
  { description: "Commerce Department", businessUnit: "B1301" },
  { description: "Animal Health Board", businessUnit: "B1401" },
  { description: "Barber Examiners Board", businessUnit: "B1501" },
  { description: "Explore Minnesota Tourism", businessUnit: "B2001" },
  { description: "Economic Security Dept", businessUnit: "B2101" },
  { description: "Employment & Economic Develop", businessUnit: "B2201" },
  { description: "DEED Grants and Projects", businessUnit: "B2202" },
  { description: "Sponsorships and Memberships", businessUnit: "B2203" },
  { description: "SSB", businessUnit: "B2204" },
  { description: "Public Facilities Authority", businessUnit: "B2401" },
  { description: "Science & Technology Authority", businessUnit: "B2501" },
  { description: "Climate Innovn Finance Authrty", businessUnit: "B2601" },
  { description: "Housing Finance Agency", businessUnit: "B3401" },
  { description: "Workers' Comp Court of Appeals", businessUnit: "B4101" },
  { description: "Labor and Industry Department", businessUnit: "B4201" },
  { description: "OSHA Compliance", businessUnit: "B4202" },
  { description: "BPV, Boats & Hobby Boiler", businessUnit: "B4203" },
  { description: "WC Vocational Rehab Unit", businessUnit: "B4204" },
  { description: "Labor Standards", businessUnit: "B4205" },
  { description: "WC Compliance, Records & Train", businessUnit: "B4206" },
  { description: "WC Special Compensation Fund", businessUnit: "B4207" },
  { description: "WC ALTERNATIVE DISPUTE RESOLUT", businessUnit: "B4208" },
  { description: "Iron Range Resources", businessUnit: "B4301" },
  { description: "Architecture, Engineering Bd", businessUnit: "B7E01" },
  { description: "Combative Sports Commission", businessUnit: "B7G01" },
  { description: "Accountancy Board", businessUnit: "B7P01" },
  { description: "Private Detectives Board", businessUnit: "B7S01" },
  { description: "Public Utilities Commission", businessUnit: "B8201" },
  { description: "Amateur Sports Commission", businessUnit: "B9D01" },
  { description: "Agriculture Utilization Resrch", businessUnit: "B9V01" },
  { description: "MNDOT District 3 Baxter", businessUnit: "BA000" },
  { description: "MNDOT District 3 Remer", businessUnit: "BA413" },
  { description: "MNDOT District 3 Motley", businessUnit: "BA415" },
  { description: "MNDOT District 3 Little Falls", businessUnit: "BA419" },
  { description: "MNDOT District 3 Aitkin", businessUnit: "BA438" },
  { description: "MNDOT District 3 Pine River", businessUnit: "BA442" },
  { description: "MNDOT District 3 Baxter Maint", businessUnit: "BA443" },
  { description: "MNDOT District 3 Isle", businessUnit: "BA445" },
  { description: "MNDOT District 3 Wadena", businessUnit: "BA450" },
  { description: "MNDOT District 3 Long Prairie", businessUnit: "BA458" },
  { description: "MNDOT District 3 Garrison", businessUnit: "BA462" },
  { description: "MNDOT District 3 Little Falls", businessUnit: "BA468" },
  { description: "MNDOT District 3 Isle", businessUnit: "BA471" },
  { description: "MNDOT District 3 Sign Shop", businessUnit: "BA999" },
  { description: "MNDOT District 2 Bemidji", businessUnit: "BJ000" },
  { description: "MNDOT District 2 Talmoon", businessUnit: "BJ136" },
  { description: "MNDOT District 2 Yard", businessUnit: "BJ300" },
  { description: "MNDOT District 2 Walker", businessUnit: "BJ316" },
  { description: "MNDOT District 2 Bagley", businessUnit: "BJ317" },
  { description: "MNDOT District 2 Bridge", businessUnit: "BJ318" },
  { description: "MNDOT District 2 Deer River", businessUnit: "BJ319" },
  { description: "MNDOT DIstrict 2 Baudette", businessUnit: "BJ320" },
  { description: "MNDOT District 2 Grygla", businessUnit: "BJ321" },
  { description: "MNDOT District 2 Northome", businessUnit: "BJ322" },
  { description: "MNDOT District 2 Roseau", businessUnit: "BJ323" },
  { description: "MNDOT District 2 Park Rapids", businessUnit: "BJ329" },
  { description: "MNDOT District 2", businessUnit: "BJ330" },
  { description: "MNDOT District 2 Sign Shop", businessUnit: "BJ999" },
  { description: "MNDOT Central Map Sales", businessUnit: "CM000" },
  { description: "MNDOT Central Office Inventory", businessUnit: "CO000" },
  { description: "MNDOT CO International", businessUnit: "CO777" },
  { description: "MNDOT District 2 Crookston", businessUnit: "CR000" },
  { description: "MNDOT District 2 Warren", businessUnit: "CR511" },
  { description: "MNDOT Dist 2 Theif River Falls", businessUnit: "CR512" },
  { description: "MNDOT District 2 Hallock", businessUnit: "CR516" },
  { description: "MNDOT District 2 Ada", businessUnit: "CR517" },
  { description: "MNDOT District 2 Erskine", businessUnit: "CR524" },
  { description: "MNDOT District 2 Karlstad", businessUnit: "CR526" },
  { description: "MNDOT Dist 2 East Grand Forks", businessUnit: "CR528" },
  { description: "MNDOT District 2 Crookston", businessUnit: "CR530" },
  { description: "MNDOT District 2 Sign Shop", businessUnit: "CR999" },
  { description: "MNDOT Central Shop", businessUnit: "CS000" },
  { description: "MNDOT Central Shop Plow Comp", businessUnit: "CS111" },
  { description: "MNDOT District 4", businessUnit: "DL000" },
  { description: "MNDOT District 4 Brknrdge", businessUnit: "DL611" },
  { description: "MNDOT District 4 Fergus Falls", businessUnit: "DL615" },
  { description: "MNDOT District 4 DL TS", businessUnit: "DL616" },
  { description: "MNDOT District 4 Moorhead", businessUnit: "DL623" },
  { description: "MNDOT District 4 Barnsville", businessUnit: "DL624" },
  { description: "MNDOT District 4 Perham", businessUnit: "DL625" },
  { description: "MNDOT District 4 Hawley", businessUnit: "DL629" },
  { description: "MNDOT District 4 Henning", businessUnit: "DL636" },
  { description: "MNDOT District 4 Mahnomen", businessUnit: "DL640" },
  { description: "MNDOT District 4 Pelican Rapid", businessUnit: "DL654" },
  { description: "MNDOT DOT DIST 4 ERHARD PIT", businessUnit: "DL771" },
  { description: "MNDOT District 4 FF Field Mech", businessUnit: "DL915" },
  { description: "MNDOT District 4 DL Field Mech", businessUnit: "DL916" },
  { description: "MNDOT District 4 Sign Shop", businessUnit: "DL999" },
  { description: "MNDOT District 1 Duluth", businessUnit: "DU000" },
  { description: "MNDOT Dist 1 West Field Mech", businessUnit: "DU002" },
  { description: "MNDOT Dist 1 North Field Mech", businessUnit: "DU003" },
  { description: "MNDOT Dist 1 East Field Mech", businessUnit: "DU004" },
  { description: "MNDOT Dist 1 CNTL Field Mech", businessUnit: "DU005" },
  { description: "MNDOT DIST 1 South Field Mech", businessUnit: "DU006" },
  { description: "MNDOT Distric 1 Floodwood Aggr", businessUnit: "DU023" },
  { description: "MNDOT District 1 McGrath Aggr", businessUnit: "DU034" },
  { description: "MNDOT District 1 Canyon Salt S", businessUnit: "DU111" },
  { description: "MNDOT District 1 Grand Rapids", businessUnit: "DU143" },
  { description: "MNDOT District 1 Arbo Salt Shd", businessUnit: "DU200" },
  { description: "MNDOT District 1 BF Salt Shed", businessUnit: "DU210" },
  { description: "MNDOT District 1 Grand Marais", businessUnit: "DU211" },
  { description: "MNDOT District 1 Thompson Hill", businessUnit: "DU218" },
  { description: "MNDOT District 1 Silver S Salt", businessUnit: "DU219" },
  { description: "MNDOT District 1 Jacobson Salt", businessUnit: "DU220" },
  { description: "MNDOT District 1 Floodwood", businessUnit: "DU222" },
  { description: "MNDOT District 1 Lester Salt", businessUnit: "DU223" },
  { description: "MNDOT District 1 Silver Bay", businessUnit: "DU224" },
  { description: "MNDOT District 1 Libby Salt", businessUnit: "DU225" },
  { description: "MNDOT District 1 Illgen City", businessUnit: "DU226" },
  { description: "MNDOT District 1 Pine City", businessUnit: "DU229" },
  { description: "MNDOT District 1 Sandstone", businessUnit: "DU230" },
  { description: "MNDOT District 1 Talmoon Salt", businessUnit: "DU240" },
  { description: "MNDOT District 1 Two Harbors", businessUnit: "DU245" },
  { description: "MNDOT District 1 Carlton", businessUnit: "DU246" },
  { description: "MNDOT District 1 Fond Du Lac", businessUnit: "DU248" },
  { description: "MNDOT District 1 Carlton Brdg", businessUnit: "DU253" },
  { description: "MNDOT District 1 Nopeming", businessUnit: "DU256" },
  { description: "MNDOT District 1 Moose Lake", businessUnit: "DU257" },
  { description: "MNDOT District 1 Saginaw Salt", businessUnit: "DU262" },
  { description: "MNDOT District 1 McGregor", businessUnit: "DU266" },
  { description: "MNDOT District 1 Nopeming Guar", businessUnit: "DU276" },
  { description: "MNDOT District 1 Nopeming Land", businessUnit: "DU290" },
  { description: "MNDOT District 1 Metro/Pike Lk", businessUnit: "DU298" },
  { description: "MN DOT DIST 1 MOORHEAD PIT", businessUnit: "DU500" },
  { description: "MNDOT District 1 Duluth OS", businessUnit: "DU888" },
  { description: "MNDOT District 1 Sign Shop", businessUnit: "DU999" },
  { description: "Perpich Ctr For Arts Education", businessUnit: "E2501" },
  { description: "MN State Colleges/Universities", businessUnit: "E2601" },
  { description: "Education Department", businessUnit: "E3701" },
  { description: "Dept of Education –Non-Federal", businessUnit: "E3702" },
  { description: "Prof Educator Licensing Std Bd", businessUnit: "E3901" },
  { description: "Historical Society", businessUnit: "E4001" },
  { description: "Minnesota State Academies", businessUnit: "E4401" },
  { description: "Arts Board", businessUnit: "E5001" },
  { description: "Office of Higher Education", businessUnit: "E6001" },
  { description: "Zoological Board", businessUnit: "E7701" },
  { description: "University of Minnesota", businessUnit: "E8101" },
  { description: "Humanities Center", businessUnit: "E9501" },
  { description: "Science Museum", businessUnit: "E9701" },
  { description: "Higher Ed Facilities Authority", businessUnit: "E9W01" },
  { description: "MNDOT Elect. Comm Oakdale", businessUnit: "EC000" },
  { description: "MNDOT Elect. Comm Duluth", businessUnit: "EC010" },
  { description: "MNDOT Elect. Comm VA", businessUnit: "EC020" },
  { description: "MNDOT Elect. Comm TRF", businessUnit: "EC030" },
  { description: "MNDOT Elect. Comm Brainerd", businessUnit: "EC040" },
  { description: "MNDOT Elect. Comm St. Cloud", businessUnit: "EC050" },
  { description: "MNDOT Elect Comm Willmar", businessUnit: "EC054" },
  { description: "MNDOT Elect. Comm DL", businessUnit: "EC060" },
  { description: "MNDOT Elect. Comm GV", businessUnit: "EC070" },
  { description: "MNDOT Elect. Comm Rochester", businessUnit: "EC080" },
  { description: "MNDOT Elect. Comm Owatonna", businessUnit: "EC084" },
  { description: "MNDOT Elect. Comm Mankato", businessUnit: "EC090" },
  { description: "MNDOT Elect Comm Marshall", businessUnit: "EC100" },
  { description: "MNDOT Elect. Comm Oakdale", businessUnit: "EC110" },
  { description: "MNDOT Elect. Comm Waters Edge", businessUnit: "EC115" },
  { description: "MNDOT Elect. Comm Grand Rapids", businessUnit: "EC120" },
  { description: "MNDOT Elect. Comm Bemidji", businessUnit: "EC130" },
  { description: "MNDOT Elect. Comm Windom", businessUnit: "EC160" },
  { description: "MNDOT Electrical Services", businessUnit: "ES000" },
  { description: "MNDOT Electrical Services 1", businessUnit: "ES001" },
  { description: "Administration Department", businessUnit: "G0201" },
  { description: "Mn Geospatial Info Office", businessUnit: "G0202" },
  { description: "Minnesota Bookstore", businessUnit: "G0203" },
  { description: "Central Mail", businessUnit: "G0204" },
  { description: "Parking", businessUnit: "G0205" },
  { description: "Materials Transfer", businessUnit: "G0206" },
  { description: "Surplus Services", businessUnit: "G0207" },
  { description: "Fleet Services", businessUnit: "G0208" },
  { description: "Admin - Facilities Management", businessUnit: "G0209" },
  { description: "Admin/State Procurement", businessUnit: "G0210" },
  { description: "Admin - Real Estate & Constr", businessUnit: "G0211" },
  { description: "Admin - Risk Management", businessUnit: "G0212" },
  { description: "Risk Management - Workers Comp", businessUnit: "G0213" },
  { description: "Financial Mgmt & Reporting", businessUnit: "G0214" },
  { description: "Data Practices Office", businessUnit: "G0215" },
  { description: "Admin FMR Smart", businessUnit: "G0216" },
  { description: "Admin HR Smart", businessUnit: "G0217" },
  { description: "Admin Demography", businessUnit: "G0218" },
  { description: "State Hist Preservation Office", businessUnit: "G0219" },
  { description: "Office of State Archaeology", businessUnit: "G0220" },
  { description: "Lottery", businessUnit: "G0301" },
  { description: "Racing Commission", businessUnit: "G0501" },
  { description: "Attorney General", businessUnit: "G0601" },
  { description: "Gambling Control Board", businessUnit: "G0901" },
  { description: "Minnesota Management & Budget", businessUnit: "G1001" },
  { description: "SEGIP", businessUnit: "G1002" },
  { description: "Admin Cap Project & Relocation", businessUnit: "G1601" },
  { description: "Human Rights Department", businessUnit: "G1701" },
  { description: "Indian Affairs Council", businessUnit: "G1901" },
  { description: "Investment Board", businessUnit: "G3801" },
  { description: "Governors Office", businessUnit: "G3901" },
  { description: "Mediation Services Department", businessUnit: "G4501" },
  { description: "MN.IT", businessUnit: "G4601" },
  { description: "Secretary of State", businessUnit: "G5301" },
  { description: "Office of State Auditor", businessUnit: "G6101" },
  { description: "Minn State Retirement System", businessUnit: "G6201" },
  { description: "Public Employees Retire Assoc", businessUnit: "G6301" },
  { description: "PERA - US BANK", businessUnit: "G6302" },
  { description: "Revenue Department", businessUnit: "G6701" },
  { description: "Teachers Retirement Assoc", businessUnit: "G6901" },
  { description: "MN Secure Choice Retirement Bd", businessUnit: "G7001" },
  { description: "MMB Higher Education", businessUnit: "G8H01" },
  { description: "MMB Intergovernmental Aids", businessUnit: "G8S01" },
  { description: "Revenue Intergovt Payments", businessUnit: "G9001" },
  { description: "Ombudsperson for Families", businessUnit: "G9201" },
  { description: "Ombud American Indian Families", businessUnit: "G9301" },
  { description: "Uniform Laws Commission", businessUnit: "G9601" },
  { description: "Campaign Finance Board", businessUnit: "G9J01" },
  { description: "Administrative Hearings", businessUnit: "G9K01" },
  { description: "Council for Minnesotans of Afr", businessUnit: "G9L01" },
  { description: "Minnesota Council on Latino Af", businessUnit: "G9M01" },
  { description: "Asian Pacific Council", businessUnit: "G9N01" },
  { description: "LGBTQIA2S+ Minnesotans Council", businessUnit: "G9P01" },
  { description: "MMB Debt Service", businessUnit: "G9Q01" },
  { description: "MMB Non-Operating", businessUnit: "G9R01" },
  { description: "MMB Treasury Non Operating", businessUnit: "G9T01" },
  { description: "Rare Disease Advisory Council", businessUnit: "G9V01" },
  { description: "Capitol Area Architect", businessUnit: "G9X01" },
  { description: "MN State Council on Disability", businessUnit: "G9Y01" },
  { description: "ACH Clearing", businessUnit: "GCA01" },
  { description: "MNDOT Metro District GV", businessUnit: "GF000" },
  { description: "MNDOT Metro Dist. Cedar Fuel", businessUnit: "GF110" },
  { description: "MNDOT Metro Dist. GV Mech", businessUnit: "GF111" },
  { description: "MNDOT Metro Dist. Shak Fuel", businessUnit: "GF129" },
  { description: "MNDOT Metro Dist. Camden Fuel", businessUnit: "GF130" },
  { description: "MNDOT Metro Dist. GV Fuel", businessUnit: "GF131" },
  { description: "MNDOT Metro Dist. Jordan Fuel", businessUnit: "GF133" },
  { description: "MNDOT Metro Dist. Anoka Fuel", businessUnit: "GF140" },
  { description: "MNDOT Metro Dist. PLY Fuel", businessUnit: "GF163" },
  { description: "MNDOT Metro Dist. SLP Fuel", businessUnit: "GF179" },
  { description: "MNDOT Metro Dist. EP Fuel", businessUnit: "GF186" },
  { description: "MNDOT Metro Dist. MG Fuel", businessUnit: "GF187" },
  { description: "MNDOT Metro Dist. EP Fuel", businessUnit: "GF196" },
  { description: "MNDOT Metro Dist Chaska Mech", businessUnit: "GF222" },
  { description: "MNDOT Metro Dist. Camden TS", businessUnit: "GF333" },
  { description: "MNDOT Metro Dist. EP TS", businessUnit: "GF444" },
  { description: "MNDOT Metro Dist. Cedar Mech", businessUnit: "GF555" },
  { description: "MAPLE GROVE FIELD MECH TRUCK", businessUnit: "GF665" },
  { description: "MNDOT Metro Dist. MG TS", businessUnit: "GF666" },
  { description: "MNDOT Metro Dist GF Mech TR", businessUnit: "GF667" },
  { description: "MNDOT Metro Dist. PLY TS", businessUnit: "GF777" },
  { description: "MNDOT METRO DIST. SLP TS", businessUnit: "GF888" },
  { description: "MNDOT Metro Dist. Cedar TS", businessUnit: "GF910" },
  { description: "MNDOT Metro Dist Chaska Maint", businessUnit: "GF926" },
  { description: "MNDOT Metro Dist. Shak TS", businessUnit: "GF929" },
  { description: "MNDOT Metro Dist. Camden TS", businessUnit: "GF930" },
  { description: "MNDOT Metro Dist GV TS", businessUnit: "GF931" },
  { description: "MNDOT Metro Dist. Jordan TS", businessUnit: "GF933" },
  { description: "MNDOT Metro Dist. Anoka TS", businessUnit: "GF940" },
  { description: "MNDOT Metro Dist PLY TS", businessUnit: "GF963" },
  { description: "MNDOT Metro Dist. SLP TS", businessUnit: "GF979" },
  { description: "MNDOT Metro Dist. EP TS", businessUnit: "GF986" },
  { description: "MNDOT Metro Dist. MG TS", businessUnit: "GF987" },
  { description: "MNDOT Metro Dist. GV Sign", businessUnit: "GF999" },
  { description: "Payroll Clearing", businessUnit: "GPR01" },
  { description: "Health Department", businessUnit: "H1201" },
  { description: "Direct Care and Treatment", businessUnit: "H5101" },
  { description: "DCT Billing", businessUnit: "H5110" },
  { description: "MSI Billing", businessUnit: "H5111" },
  { description: "Human Services Department", businessUnit: "H5501" },
  { description: "Grants and Projects", businessUnit: "H5502" },
  { description: "HealthCare Recoveries", businessUnit: "H5503" },
  { description: "Other Counties and Tribes", businessUnit: "H5504" },
  { description: "Parent Fees", businessUnit: "H5505" },
  { description: "Parent Usage", businessUnit: "H5506" },
  { description: "Estate Claims", businessUnit: "H5507" },
  { description: "Licensing", businessUnit: "H5508" },
  { description: "DHS Other", businessUnit: "H5509" },
  { description: "SOS Business Office", businessUnit: "H5510" },
  { description: "MSOP Business Office", businessUnit: "H5511" },
  { description: "MAEPD", businessUnit: "H5512" },
  { description: "Alternative Care", businessUnit: "H5513" },
  { description: "MSHO", businessUnit: "H5514" },
  { description: "MDHO", businessUnit: "H5515" },
  { description: "Special Needs Basic Care", businessUnit: "H5516" },
  { description: "Nursing Home Surcharge", businessUnit: "H5517" },
  { description: "Hospital Surcharge", businessUnit: "H5518" },
  { description: "HMO Surcharge", businessUnit: "H5519" },
  { description: "ICFDD Surcharge", businessUnit: "H5520" },
  { description: "ECPN", businessUnit: "H5521" },
  { description: "SIRS", businessUnit: "H5522" },
  { description: "MinnesotaCare Operations", businessUnit: "H5523" },
  { description: "NSR", businessUnit: "H5524" },
  { description: "MinnesotaCare Overpayments", businessUnit: "H5525" },
  { description: "PROVIDER CREDIT BALANCES", businessUnit: "H5526" },
  { description: "DHS - DOR Collections", businessUnit: "H5599" },
  { description: "Children Youth & Families Dept", businessUnit: "H5801" },
  { description: "MN Insurance Marketplace", businessUnit: "H6001" },
  { description: "MNsure", businessUnit: "H6002" },
  { description: "Veterans Affairs Department", businessUnit: "H7501" },
  { description: "Medical Practice Board", businessUnit: "H7B01" },
  { description: "Nursing Board", businessUnit: "H7C01" },
  { description: "Pharmacy Board", businessUnit: "H7D01" },
  { description: "Dentistry Board", businessUnit: "H7F01" },
  { description: "Chiropractic Examiners Board", businessUnit: "H7H01" },
  { description: "Optometry Board", businessUnit: "H7J01" },
  { description: "Exec for LT Svcs & Supports Bd", businessUnit: "H7K01" },
  { description: "Social Work Board", businessUnit: "H7L01" },
  { description: "Marriage and Family Therapy Bd", businessUnit: "H7M01" },
  { description: "Podiatric Medicine", businessUnit: "H7Q01" },
  { description: "Veterinary Medicine Board", businessUnit: "H7R01" },
  { description: "Emergency Medical Services Off", businessUnit: "H7S01" },
  { description: "Dietetics & Nutrition Practice", businessUnit: "H7U01" },
  { description: "Psychology Board", businessUnit: "H7V01" },
  { description: "Physical Therapy Board", businessUnit: "H7W01" },
  { description: "Behavioral Health & Therapy Bd", businessUnit: "H7X01" },
  { description: "Occupational Therapy Pract Bd", businessUnit: "H7Y01" },
  { description: "Foster Youth Ombudsperson", businessUnit: "H8A01" },
  { description: "Emergency Medical Services Off", businessUnit: "H8S01" },
  { description: "Ombudsman MH/DD", businessUnit: "H9G01" },
  { description: "Trial Courts", businessUnit: "J3301" },
  { description: "STATE COMPETENCY ATTAINMENT BD", businessUnit: "J4001" },
  { description: "State Guardian Ad Litem", businessUnit: "J5001" },
  { description: "Public Defense Board", businessUnit: "J5201" },
  { description: "Court of Appeals", businessUnit: "J5801" },
  { description: "Appellate Counsel & Trg Office", businessUnit: "J6101" },
  { description: "State Board of Civil Legal Aid", businessUnit: "J6301" },
  { description: "Supreme Court", businessUnit: "J6501" },
  { description: "Tax Court", businessUnit: "J6801" },
  { description: "Judicial Standards Board", businessUnit: "J7001" },
  { description: "Legislature Coordinating Comm", businessUnit: "L1001" },
  { description: "Senate", businessUnit: "L1101" },
  { description: "House", businessUnit: "L1201" },
  { description: "Legislative Auditor", businessUnit: "L4901" },
  { description: "MDH/MDA Lab", businessUnit: "LAB00" },
  { description: "MNDOT District 7 Mankato", businessUnit: "MK000" },
  { description: "MNDOT District 7 Blue Earth TS", businessUnit: "MK415" },
  { description: "MNDOT District 7 Wells TS", businessUnit: "MK416" },
  { description: "MNDOT District 7 St. Peter TS", businessUnit: "MK418" },
  { description: "MNDOT District 7 Waseca TS", businessUnit: "MK421" },
  { description: "MNDOT District 7 Mapleton TS", businessUnit: "MK423" },
  { description: "MNDOT District 7 Courtland TS", businessUnit: "MK424" },
  { description: "MNDOT District 7 LeSueur TS", businessUnit: "MK430" },
  { description: "MNDOT District 7 Montgomery TS", businessUnit: "MK437" },
  { description: "MNDOT District 7 Gaylord TS", businessUnit: "MK438" },
  { description: "MNDOT District 7 Green Isle TS", businessUnit: "MK492" },
  { description: "MNDOT District 7 Field Mech", businessUnit: "MK494" },
  { description: "MNDOT District 7 Mankato Yard", businessUnit: "MK700" },
  { description: "MNDOT District 7 Watervil Salt", businessUnit: "MK717" },
  { description: "MNDOT District 7 Alden Salt", businessUnit: "MK718" },
  { description: "MNDOT District 7 Mankato Brg", businessUnit: "MK997" },
  { description: "MNDOT Dist 7 Mankato Sign Shop", businessUnit: "MK999" },
  { description: "MNDOT District 8 Marshall", businessUnit: "ML000" },
  { description: "MNDOT District 8 Marshall Sign", businessUnit: "ML999" },
  { description: "State of Minnesota", businessUnit: "MN001" },
  { description: "MNDOT District 4 Morris", businessUnit: "MO000" },
  { description: "MNDOT District 4 Wheaton Pit", businessUnit: "MO781" },
  { description: "MNDOT District 4 Graceville Pi", businessUnit: "MO782" },
  { description: "MNDOT DISTRICT 4 BRUSHVALE PIT", businessUnit: "MO783" },
  { description: "MNDOT District 4 Appleton", businessUnit: "MO802" },
  { description: "MNDOT District 4 Wheaton", businessUnit: "MO806" },
  { description: "MNDOT District 4 Beardsley", businessUnit: "MO807" },
  { description: "MNDOT District 4 Glenwood", businessUnit: "MO808" },
  { description: "MNDOT District 4 Barrett Salt", businessUnit: "MO809" },
  { description: "MNDOT District 4 Evansville", businessUnit: "MO816" },
  { description: "MNDOT District 4 Alexanndria", businessUnit: "MO818" },
  { description: "MNDOT District 4 Ortonville", businessUnit: "MO819" },
  { description: "MNDOT District 4 Morris HQ", businessUnit: "MO820" },
  { description: "MNDOT District 4 Morris Cold", businessUnit: "MO821" },
  { description: "MNDOT District 4 Benson", businessUnit: "MO822" },
  { description: "MNDOT District 4 Morris Bldg", businessUnit: "MO900" },
  { description: "MNDOT District 4 Morris East", businessUnit: "MO907" },
  { description: "MNDOT District 4 Morris West", businessUnit: "MO908" },
  { description: "MNDOT District 4 Alexandria", businessUnit: "MO918" },
  { description: "MNDOT District 4 Sign Shop", businessUnit: "MO999" },
  { description: "MNDOT Metro Dist. Oakdale", businessUnit: "OD000" },
  { description: "MNDOT Metro Dist Maryland Mech", businessUnit: "OD111" },
  { description: "MNDOT Metro Dist Maplewood", businessUnit: "OD117" },
  { description: "MNDOT Metro Dist. AH TS", businessUnit: "OD118" },
  { description: "MNDOT Metro Dist Oak TS", businessUnit: "OD138" },
  { description: "MNDOT Metro Dist FL TS", businessUnit: "OD139" },
  { description: "MNDOT Metro Dist. NB TS", businessUnit: "OD140" },
  { description: "MNDOT Metro Dist. Lakeville TS", businessUnit: "OD141" },
  { description: "MNDOT Metro Dist. Mendota TS", businessUnit: "OD152" },
  { description: "MNDOT Metro Dist. Hastings TS", businessUnit: "OD153" },
  { description: "MNDOT Metro Dist. Maryland TS", businessUnit: "OD165" },
  { description: "MNDOT Metro Dist Hasting Mech", businessUnit: "OD222" },
  { description: "MNDOT Metro Dist FL Mech", businessUnit: "OD333" },
  { description: "MNDOT Metro Dist Oak Mech", businessUnit: "OD444" },
  { description: "MNDOT Metro Dist OD Mech TR", businessUnit: "OD445" },
  { description: "MNDOT Metro Dist. Hasting Mech", businessUnit: "OD555" },
  { description: "MNDOT Metro Dist. AH Mech", businessUnit: "OD666" },
  { description: "MNDOT Metro Mendota Mech", businessUnit: "OD777" },
  { description: "MNDOT Dist Oak Sign", businessUnit: "OD999" },
  { description: "MNDOT Sign Shop", businessUnit: "OS000" },
  { description: "MNDOT Sign Shop Finished Goods", businessUnit: "OS001" },
  { description: "MNDOT District 6 Owatonna", businessUnit: "OW000" },
  { description: "MNDOT District 6 Austin Stock", businessUnit: "OW301" },
  { description: "MNDOT District 6 AlbertLea SP", businessUnit: "OW302" },
  { description: "MNDOT District 6 Redwing Stock", businessUnit: "OW303" },
  { description: "MNDOT District 6 Owatonna Stoc", businessUnit: "OW305" },
  { description: "MNDOT District 6 Northfield", businessUnit: "OW317" },
  { description: "MNDOT District 6 Albert Lea", businessUnit: "OW319" },
  { description: "MNDOT District 6 Faribault", businessUnit: "OW328" },
  { description: "MNDOT District 6 Cannon Falls", businessUnit: "OW331" },
  { description: "MNDOT District 6 Zumbrota", businessUnit: "OW339" },
  { description: "MNDOT District 6 Austin", businessUnit: "OW349" },
  { description: "MNDOT District 6 Redwing", businessUnit: "OW354" },
  { description: "MNDOT District 6 Dodge Center", businessUnit: "OW361" },
  { description: "MNDOT DIST 6 BLOOMING PR SALT", businessUnit: "OW659" },
  { description: "MNDOT DIST 6 FARIBAULT SALT", businessUnit: "OW662" },
  { description: "MNDOT DIST 6 KASSON SALT", businessUnit: "OW663" },
  { description: "MN DOT DIST 6 LE ROY SALT SHED", businessUnit: "OW664" },
  { description: "MNDOT District 6 Sign Shop", businessUnit: "OW999" },
  { description: "Military Affairs Department", businessUnit: "P0101" },
  { description: "Public Safety Department", businessUnit: "P0701" },
  { description: "Homeland Security", businessUnit: "P0702" },
  { description: "BCA", businessUnit: "P0703" },
  { description: "Fire Marshal", businessUnit: "P0704" },
  { description: "State Patrol", businessUnit: "P0705" },
  { description: "AGED", businessUnit: "P0706" },
  { description: "DVS", businessUnit: "P0707" },
  { description: "Pipeline Safety", businessUnit: "P0708" },
  { description: "Ombudsperson for Corrections", businessUnit: "P0801" },
  { description: "Corrections Department", businessUnit: "P7801" },
  { description: "Peace Officers Board (POST)", businessUnit: "P7T01" },
  { description: "Cannabis Expungement Board", businessUnit: "P8001" },
  { description: "Clemency Review Commission", businessUnit: "P8201" },
  { description: "Sentencing Guidelines Comm", businessUnit: "P9E01" },
  { description: "Minn Conservation Corps", businessUnit: "R2801" },
  { description: "Natural Resources Department", businessUnit: "R2901" },
  { description: "Pollution Control Agency", businessUnit: "R3201" },
  { description: "Water and Soil Resources Board", businessUnit: "R9P01" },
  { description: "MNDOT District 6 Rochester", businessUnit: "RO000" },
  { description: "MNDOT Dist 6 Rochester Bridge", businessUnit: "RO109" },
  { description: "MNDOT District 6 Winona", businessUnit: "RO218" },
  { description: "MNDOT District 6 Winona Bridge", businessUnit: "RO219" },
  { description: "MNDOT District 6 Stewartville", businessUnit: "RO220" },
  { description: "MNDOT District 6 St. Charles", businessUnit: "RO229" },
  { description: "MNDOT District 6 Dresbach", businessUnit: "RO252" },
  { description: "MNDOT DIST 6 ROCHESTER MAINT", businessUnit: "RO270" },
  { description: "MN DOT DIST 6 RUSHFORD SALT SH", businessUnit: "RO601" },
  { description: "MNDOT District 6 Chatfield", businessUnit: "RO602" },
  { description: "MNDOT District 6 Caledonia", businessUnit: "RO603" },
  { description: "MNDOT District 6 La Cresent", businessUnit: "RO605" },
  { description: "MNDOT District 6 Houston", businessUnit: "RO606" },
  { description: "MN DOT DIST 6 PRESTON SALT SHE", businessUnit: "RO607" },
  { description: "MNDOT District 6 Spring Valley", businessUnit: "RO609" },
  { description: "MN DOT DIST 6 WABASHA SALT SHE", businessUnit: "RO611" },
  { description: "MN DOT DIST 6 WILSON SALT SHED", businessUnit: "RO614" },
  { description: "MNDOT District 6 Sign Shop", businessUnit: "RO999" },
  { description: "MNDOT District 3 St. Cloud", businessUnit: "SC000" },
  { description: "MNDOT DISTRICT 3 ISLE", businessUnit: "SC471" },
  { description: "MNDOT District 3 Paynesville", businessUnit: "SC707" },
  { description: "MNDOT District 3 Cambridge", businessUnit: "SC708" },
  { description: "MNDOT District 3 Mora", businessUnit: "SC713" },
  { description: "MNDOT District 3 Foley", businessUnit: "SC714" },
  { description: "CLEARWATER TRUCK STATION", businessUnit: "SC715" },
  { description: "MNDOT Distric 3 Albany", businessUnit: "SC740" },
  { description: "MNDOT Distric 3 Elk River", businessUnit: "SC741" },
  { description: "MNDOT District 3 Monticello", businessUnit: "SC742" },
  { description: "MNDOT District 3 Milaca", businessUnit: "SC749" },
  { description: "MNDOT District 3 Buffalo", businessUnit: "SC753" },
  { description: "MNDOT District 3 Sauk Centre", businessUnit: "SC772" },
  { description: "MNDOT Dist 3 St. Cloud Maint", businessUnit: "SC900" },
  { description: "MNDOT District 3 Sign Shop", businessUnit: "SC999" },
  { description: "MDH Support Services Center", businessUnit: "SSC00" },
  { description: "Transportation Department", businessUnit: "T7901" },
  { description: "Transportation Restitution", businessUnit: "T7902" },
  { description: "Transportation Misc Interest", businessUnit: "T7903" },
  { description: "Transportation Joint Projects", businessUnit: "T7904" },
  { description: "Transportation Project Billing", businessUnit: "T79FA" },
  { description: "Metropolitan Council/Transport", businessUnit: "T9B01" },
  { description: "MNDOT District 1 Virginia", businessUnit: "VA000" },
  { description: "HIBBING WEST FIELD MECHANIC", businessUnit: "VA002" },
  { description: "MNDOT District 1 Cook", businessUnit: "VA012" },
  { description: "MNDOT District 1 Ely", businessUnit: "VA022" },
  { description: "MNDOT District 1 VA Salt Sand", businessUnit: "VA023" },
  { description: "MNDOT District 1 VA Guardrail", businessUnit: "VA027" },
  { description: "MNDOT District 1 Little Fork", businessUnit: "VA033" },
  { description: "MNDOT District 1 Intl Falls", businessUnit: "VA040" },
  { description: "MNDOT District 1 Hibbing", businessUnit: "VA055" },
  { description: "MNDOT District 1 Deer Lake", businessUnit: "VA056" },
  { description: "MNDOT District 1 Biwabik", businessUnit: "VA100" },
  { description: "MNDOT District 1 Melrude", businessUnit: "VA120" },
  { description: "MNDOT District 1 Tower", businessUnit: "VA130" },
  { description: "MNDOT District 1 Big Falls", businessUnit: "VA300" },
  { description: "MNDOT District 1 Buck Lake", businessUnit: "VA310" },
  { description: "MNDOT District 1 Kinmount", businessUnit: "VA320" },
  { description: "MN DOT DIST 1 TOGO PIT", businessUnit: "VA500" },
  { description: "MNDOT District 1 Angora", businessUnit: "VA700" },
  { description: "MNDOT District 1 Sign Shop", businessUnit: "VA999" },
  { description: "MNDOT METRO DIST ROSEVILLE IN", businessUnit: "WE000" },
  { description: "MNDOT District 7 Windom", businessUnit: "WI000" },
  { description: "MNDOT District 7 Windom Stock", businessUnit: "WI444" },
  { description: "MNDOT District 7 Windom Const", businessUnit: "WI555" },
  { description: "MNDIT District 7 Luverne", businessUnit: "WI609" },
  { description: "MNDOT District 7 Worthington", businessUnit: "WI613" },
  { description: "MNDOT District 7 Windom Yard", businessUnit: "WI614" },
  { description: "MNDOT District 7 Jackson", businessUnit: "WI616" },
  { description: "MNDOT District 7 Fairmont", businessUnit: "WI620" },
  { description: "MNDOT District 7 Sleepy Eye", businessUnit: "WI627" },
  { description: "MNDOT District 7 Adrian", businessUnit: "WI629" },
  { description: "MNDOT District 7 St. James", businessUnit: "WI632" },
  { description: "MNDOT District 7 Sherburn", businessUnit: "WI694" },
  { description: "MNDOT District 7 Madelia", businessUnit: "WI695" },
  { description: "MNDOT District 7 Windom Bridge", businessUnit: "WI697" },
  { description: "MNDOT District 7 Windom Bridge", businessUnit: "WI997" },
  { description: "MNDOT Dist 7 Windom Sign Shop", businessUnit: "WI999" },
  { description: "MNDOT District 8 Willmar", businessUnit: "WL000" },
  { description: "MNDOT District 8 Willmar Road", businessUnit: "WL023" },
  { description: "MNDOT District 8 Madison Fuel", businessUnit: "WL521" },
  { description: "MNDOT District 8 Willmar Fuel", businessUnit: "WL523" },
  { description: "MNDOT District 8 Glencoe SP", businessUnit: "WL703" },
  { description: "MNDOT Dist 8 Montevideo SP", businessUnit: "WL704" },
  { description: "MNDOT District 8 Litchfield SP", businessUnit: "WL705" },
  { description: "MNDOT District 8 Hutchinson SP", businessUnit: "WL706" },
  { description: "MNDOT District 8 Willmar Yard", businessUnit: "WL723" },
  { description: "MNDOT District 8 Pipestone SP", businessUnit: "WL802" },
  { description: "MNDOT District 8 Tracy SP", businessUnit: "WL807" },
  { description: "MNDOT District 8 Ivanhoe SP", businessUnit: "WL814" },
  { description: "MNDOT District 8 Olivia SP", businessUnit: "WL815" },
  { description: "MNDOT District 8 Madison SP", businessUnit: "WL821" },
  { description: "MNDOT District 8 Marshall SP", businessUnit: "WL823" },
  { description: "MNDOT District 8 Slayton SP", businessUnit: "WL834" },
  { description: "MNDOT Dist 8 Redwood Falls SP", businessUnit: "WL836" },
  { description: "MNDOT Dist 8 Granite Falls SP", businessUnit: "WL839" },
  { description: "MNDOT District 8 Willmar Sign", businessUnit: "WL999" }
];

// Function to find business unit by description
export const findBusinessUnitByDescription = (description: string): BusinessUnit | undefined => {
  return businessUnits.find(unit => unit.description === description);
};

// Function to find business unit by business unit code
export const findBusinessUnitByCode = (businessUnit: string): BusinessUnit | undefined => {
  return businessUnits.find(unit => unit.businessUnit === businessUnit);
};