/*
  # Create agency business units table with CSV data

  1. New Tables
    - `agency_business_units`
      - `id` (uuid, primary key)
      - `agency_code` (character(3), not null)
      - `agency_name` (text, not null)
      - `business_unit_code` (character(5), not null)
      - `business_unit_name` (text, not null)
      - `created_at` (timestamp)

  2. Security
    - Enable RLS on `agency_business_units` table
    - Add policy for public read access

  3. Data Import
    - Import all business unit data from CSV
    - Map to correct agency codes and names

  4. Indexes and Constraints
    - Index on agency_code for fast filtering
    - Unique constraint on agency_code + business_unit_code
*/

-- Create the agency_business_units table
CREATE TABLE IF NOT EXISTS public.agency_business_units (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_code character(3) NOT NULL,
  agency_name text NOT NULL,
  business_unit_code character(5) NOT NULL,
  business_unit_name text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.agency_business_units ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Allow public read access to agency business units" 
  ON public.agency_business_units 
  FOR SELECT 
  USING (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_agency_business_units_agency_code 
  ON public.agency_business_units (agency_code);

-- Create unique constraint to prevent duplicates
CREATE UNIQUE INDEX IF NOT EXISTS unique_agency_business_unit 
  ON public.agency_business_units (agency_code, business_unit_code);

-- Insert all business unit data from CSV
INSERT INTO public.agency_business_units (business_unit_code, business_unit_name, agency_name, agency_code) VALUES
('B0401', 'Agriculture Department', 'MN Department of Agriculture', 'B04'),
('B0402', 'Agriculture Dept - US Bank', 'MN Department of Agriculture', 'B04'),
('B1001', 'Office of Cannabis Management', 'MN Office of Cannabis Management', 'B10'),
('B1101', 'Cosmetologist Examiners Board', 'MN Board of Cosmetology', 'B11'),
('B1301', 'Commerce Department', 'MN Department of Commerce', 'B13'),
('B1401', 'Animal Health Board', 'MN Board of Animal Health', 'B14'),
('B1501', 'Barber Examiners Board', 'MN Board of Barber Examiners', 'B15'),
('B2001', 'Explore Minnesota Tourism', 'Explore Minnesota Tourism', 'B20'),
('B2101', 'Economic Security Dept', 'MN Department of Employment & Economic Development', 'B21'),
('B2201', 'Employment & Economic Develop', 'MN Department of Employment & Economic Development', 'B22'),
('B2202', 'DEED Grants and Projects', 'MN Department of Employment & Economic Development', 'B22'),
('B2203', 'Sponsorships and Memberships', 'MN Department of Employment & Economic Development', 'B22'),
('B2204', 'SSB', 'MN Department of Employment & Economic Development', 'B22'),
('B2401', 'Public Facilities Authority', 'MN Department of Employment & Economic Development', 'B24'),
('B2501', 'Science & Technology Authority', 'MN Department of Employment & Economic Development', 'B25'),
('B2601', 'Climate Innovn Finance Authrty', 'MN Climate Innovation Finance Authority', 'B26'),
('B3401', 'Housing Finance Agency', 'MN Housing Finance Agency', 'B34'),
('B4101', 'Workers'' Comp Court of Appeals', 'MN Workers'' Compensation Court of Appeals', 'B41'),
('B4201', 'Labor and Industry Department', 'MN Department of Labor and Industry', 'B42'),
('B4202', 'OSHA Compliance', 'MN Department of Labor and Industry', 'B42'),
('B4203', 'BPV, Boats & Hobby Boiler', 'MN Department of Labor and Industry', 'B42'),
('B4204', 'WC Vocational Rehab Unit', 'MN Department of Labor and Industry', 'B42'),
('B4205', 'Labor Standards', 'MN Department of Labor and Industry', 'B42'),
('B4206', 'WC Compliance, Records & Train', 'MN Department of Labor and Industry', 'B42'),
('B4207', 'WC Special Compensation Fund', 'MN Department of Labor and Industry', 'B42'),
('B4208', 'WC ALTERNATIVE DISPUTE RESOLUT', 'MN Department of Labor and Industry', 'B42'),
('B4301', 'Iron Range Resources', 'MN Department of Iron Range Resources & Rehabilitation', 'B43'),
('B7E01', 'Architecture, Engineering Bd', 'MN Board of AELSLAGID', 'B7E'),
('B7G01', 'Combative Sports Commission', 'MN Office of Combative Sports', 'B7G'),
('B7P01', 'Accountancy Board', 'MN Board of Accountancy', 'B7P'),
('B7S01', 'Private Detectives Board', 'The Board of Private Detective and Protective Agent Services', 'B7S'),
('B8201', 'Public Utilities Commission', 'MN Public Utilities Commission', 'B82'),
('B9D01', 'Amateur Sports Commission', 'MN Amateur Sports Commission', 'B9D'),
('B9V01', 'Agriculture Utilization Resrch', 'Agricultural Utilization Research Institute', 'B9V'),
('BA000', 'MNDOT District 3 Baxter', 'MN Department of Transportation', 'T79'),
('BA413', 'MNDOT District 3 Remer', 'MN Department of Transportation', 'T79'),
('BA415', 'MNDOT District 3 Motley', 'MN Department of Transportation', 'T79'),
('BA419', 'MNDOT District 3 Little Falls', 'MN Department of Transportation', 'T79'),
('BA438', 'MNDOT District 3 Aitkin', 'MN Department of Transportation', 'T79'),
('BA442', 'MNDOT District 3 Pine River', 'MN Department of Transportation', 'T79'),
('BA443', 'MNDOT District 3 Baxter Maint', 'MN Department of Transportation', 'T79'),
('BA445', 'MNDOT District 3 Isle', 'MN Department of Transportation', 'T79'),
('BA450', 'MNDOT District 3 Wadena', 'MN Department of Transportation', 'T79'),
('BA458', 'MNDOT District 3 Long Prairie', 'MN Department of Transportation', 'T79'),
('BA462', 'MNDOT District 3 Garrison', 'MN Department of Transportation', 'T79'),
('BA468', 'MNDOT District 3 Little Falls', 'MN Department of Transportation', 'T79'),
('BA471', 'MNDOT District 3 Isle', 'MN Department of Transportation', 'T79'),
('BA999', 'MNDOT District 3 Sign Shop', 'MN Department of Transportation', 'T79'),
('BJ000', 'MNDOT District 2 Bemidji', 'MN Department of Transportation', 'T79'),
('BJ136', 'MNDOT District 2 Talmoon', 'MN Department of Transportation', 'T79'),
('BJ300', 'MNDOT District 2 Yard', 'MN Department of Transportation', 'T79'),
('BJ316', 'MNDOT District 2 Walker', 'MN Department of Transportation', 'T79'),
('BJ317', 'MNDOT District 2 Bagley', 'MN Department of Transportation', 'T79'),
('BJ318', 'MNDOT District 2 Bridge', 'MN Department of Transportation', 'T79'),
('BJ319', 'MNDOT District 2 Deer River', 'MN Department of Transportation', 'T79'),
('BJ320', 'MNDOT DIstrict 2 Baudette', 'MN Department of Transportation', 'T79'),
('BJ321', 'MNDOT District 2 Grygla', 'MN Department of Transportation', 'T79'),
('BJ322', 'MNDOT District 2 Northome', 'MN Department of Transportation', 'T79'),
('BJ323', 'MNDOT District 2 Roseau', 'MN Department of Transportation', 'T79'),
('BJ329', 'MNDOT District 2 Park Rapids', 'MN Department of Transportation', 'T79'),
('BJ330', 'MNDOT District 2', 'MN Department of Transportation', 'T79'),
('BJ999', 'MNDOT District 2 Sign Shop', 'MN Department of Transportation', 'T79'),
('CM000', 'MNDOT Central Map Sales', 'MN Department of Transportation', 'T79'),
('CO000', 'MNDOT Central Office Inventory', 'MN Department of Transportation', 'T79'),
('CO777', 'MNDOT CO International', 'MN Department of Transportation', 'T79'),
('CR000', 'MNDOT District 2 Crookston', 'MN Department of Transportation', 'T79'),
('CR511', 'MNDOT District 2 Warren', 'MN Department of Transportation', 'T79'),
('CR512', 'MNDOT Dist 2 Theif River Falls', 'MN Department of Transportation', 'T79'),
('CR516', 'MNDOT District 2 Hallock', 'MN Department of Transportation', 'T79'),
('CR517', 'MNDOT District 2 Ada', 'MN Department of Transportation', 'T79'),
('CR524', 'MNDOT District 2 Erskine', 'MN Department of Transportation', 'T79'),
('CR526', 'MNDOT District 2 Karlstad', 'MN Department of Transportation', 'T79'),
('CR528', 'MNDOT Dist 2 East Grand Forks', 'MN Department of Transportation', 'T79'),
('CR530', 'MNDOT District 2 Crookston', 'MN Department of Transportation', 'T79'),
('CR999', 'MNDOT District 2 Sign Shop', 'MN Department of Transportation', 'T79'),
('CS000', 'MNDOT Central Shop', 'MN Department of Transportation', 'T79'),
('CS111', 'MNDOT Central Shop Plow Comp', 'MN Department of Transportation', 'T79'),
('DL000', 'MNDOT District 4', 'MN Department of Transportation', 'T79'),
('DL611', 'MNDOT District 4 Brknrdge', 'MN Department of Transportation', 'T79'),
('DL615', 'MNDOT District 4 Fergus Falls', 'MN Department of Transportation', 'T79'),
('DL616', 'MNDOT District 4 DL TS', 'MN Department of Transportation', 'T79'),
('DL623', 'MNDOT District 4 Moorhead', 'MN Department of Transportation', 'T79'),
('DL624', 'MNDOT District 4 Barnsville', 'MN Department of Transportation', 'T79'),
('DL625', 'MNDOT District 4 Perham', 'MN Department of Transportation', 'T79'),
('DL629', 'MNDOT District 4 Hawley', 'MN Department of Transportation', 'T79'),
('DL636', 'MNDOT District 4 Henning', 'MN Department of Transportation', 'T79'),
('DL640', 'MNDOT District 4 Mahnomen', 'MN Department of Transportation', 'T79'),
('DL654', 'MNDOT District 4 Pelican Rapid', 'MN Department of Transportation', 'T79'),
('DL771', 'MNDOT DOT DIST 4 ERHARD PIT', 'MN Department of Transportation', 'T79'),
('DL915', 'MNDOT District 4 FF Field Mech', 'MN Department of Transportation', 'T79'),
('DL916', 'MNDOT District 4 DL Field Mech', 'MN Department of Transportation', 'T79'),
('DL999', 'MNDOT District 4 Sign Shop', 'MN Department of Transportation', 'T79'),
('DU000', 'MNDOT District 1 Duluth', 'MN Department of Transportation', 'T79'),
('DU002', 'MNDOT Dist 1 West Field Mech', 'MN Department of Transportation', 'T79'),
('DU003', 'MNDOT Dist 1 North Field Mech', 'MN Department of Transportation', 'T79'),
('DU004', 'MNDOT Dist 1 East Field Mech', 'MN Department of Transportation', 'T79'),
('DU005', 'MNDOT Dist 1 CNTL Field Mech', 'MN Department of Transportation', 'T79'),
('DU006', 'MNDOT DIST 1 South Field Mech', 'MN Department of Transportation', 'T79'),
('DU023', 'MNDOT Distric 1 Floodwood Aggr', 'MN Department of Transportation', 'T79'),
('DU034', 'MNDOT District 1 McGrath Aggr', 'MN Department of Transportation', 'T79'),
('DU111', 'MNDOT District 1 Canyon Salt S', 'MN Department of Transportation', 'T79'),
('DU143', 'MNDOT District 1 Grand Rapids', 'MN Department of Transportation', 'T79'),
('DU200', 'MNDOT District 1 Arbo Salt Shd', 'MN Department of Transportation', 'T79'),
('DU210', 'MNDOT District 1 BF Salt Shed', 'MN Department of Transportation', 'T79'),
('DU211', 'MNDOT District 1 Grand Marais', 'MN Department of Transportation', 'T79'),
('DU218', 'MNDOT District 1 Thompson Hill', 'MN Department of Transportation', 'T79'),
('DU219', 'MNDOT District 1 Silver S Salt', 'MN Department of Transportation', 'T79'),
('DU220', 'MNDOT District 1 Jacobson Salt', 'MN Department of Transportation', 'T79'),
('DU222', 'MNDOT District 1 Floodwood', 'MN Department of Transportation', 'T79'),
('DU223', 'MNDOT District 1 Lester Salt', 'MN Department of Transportation', 'T79'),
('DU224', 'MNDOT District 1 Silver Bay', 'MN Department of Transportation', 'T79'),
('DU225', 'MNDOT District 1 Libby Salt', 'MN Department of Transportation', 'T79'),
('DU226', 'MNDOT District 1 Illgen City', 'MN Department of Transportation', 'T79'),
('DU229', 'MNDOT District 1 Pine City', 'MN Department of Transportation', 'T79'),
('DU230', 'MNDOT District 1 Sandstone', 'MN Department of Transportation', 'T79'),
('DU240', 'MNDOT District 1 Talmoon Salt', 'MN Department of Transportation', 'T79'),
('DU245', 'MNDOT District 1 Two Harbors', 'MN Department of Transportation', 'T79'),
('DU246', 'MNDOT District 1 Carlton', 'MN Department of Transportation', 'T79'),
('DU248', 'MNDOT District 1 Fond Du Lac', 'MN Department of Transportation', 'T79'),
('DU253', 'MNDOT District 1 Carlton Brdg', 'MN Department of Transportation', 'T79'),
('DU256', 'MNDOT District 1 Nopeming', 'MN Department of Transportation', 'T79'),
('DU257', 'MNDOT District 1 Moose Lake', 'MN Department of Transportation', 'T79'),
('DU262', 'MNDOT District 1 Saginaw Salt', 'MN Department of Transportation', 'T79'),
('DU266', 'MNDOT District 1 McGregor', 'MN Department of Transportation', 'T79'),
('DU276', 'MNDOT District 1 Nopeming Guar', 'MN Department of Transportation', 'T79'),
('DU290', 'MNDOT District 1 Nopeming Land', 'MN Department of Transportation', 'T79'),
('DU298', 'MNDOT District 1 Metro/Pike Lk', 'MN Department of Transportation', 'T79'),
('DU500', 'MN DOT DIST 1 MOORHEAD PIT', 'MN Department of Transportation', 'T79'),
('DU888', 'MNDOT District 1 Duluth OS', 'MN Department of Transportation', 'T79'),
('DU999', 'MNDOT District 1 Sign Shop', 'MN Department of Transportation', 'T79'),
('E2501', 'Perpich Ctr For Arts Education', 'Perpich Center for Arts Education', 'E25'),
('E2601', 'MN State Colleges/Universities', 'Minnesota State', 'E26'),
('E3701', 'Education Department', 'MN Department of Education', 'E37'),
('E3702', 'Dept of Education –Non-Federal', 'MN Department of Education', 'E37'),
('E3901', 'Prof Educator Licensing Std Bd', 'MN Professional Educator Licensing and Standards Board', 'E39'),
('E4001', 'Historical Society', 'Minnesota Historical Society', 'E40'),
('E4401', 'Minnesota State Academies', 'Minnesota State Academies for The Deaf and the Blind', 'E44'),
('E5001', 'Arts Board', 'Minnesota State Arts Board', 'E50'),
('E6001', 'Office of Higher Education', 'Minnesota Office of Higher Education', 'E60'),
('E7701', 'Zoological Board', 'MN State Zoological Board', 'E77'),
('E8101', 'University of Minnesota', 'University of Minnesota', 'E81'),
('E9501', 'Humanities Center', 'Minnesota Humanities Center', 'E95'),
('E9701', 'Science Museum', 'Science Museum of Minnesota', 'E97'),
('E9W01', 'Higher Ed Facilities Authority', 'Minnesota Higher Education Facilities Authority', 'E9W'),
('EC000', 'MNDOT Elect. Comm Oakdale', 'MN Department of Transportation', 'T79'),
('EC010', 'MNDOT Elect. Comm Duluth', 'MN Department of Transportation', 'T79'),
('EC020', 'MNDOT Elect. Comm VA', 'MN Department of Transportation', 'T79'),
('EC030', 'MNDOT Elect. Comm TRF', 'MN Department of Transportation', 'T79'),
('EC040', 'MNDOT Elect. Comm Brainerd', 'MN Department of Transportation', 'T79'),
('EC050', 'MNDOT Elect. Comm St. Cloud', 'MN Department of Transportation', 'T79'),
('EC054', 'MNDOT Elect Comm Willmar', 'MN Department of Transportation', 'T79'),
('EC060', 'MNDOT Elect. Comm DL', 'MN Department of Transportation', 'T79'),
('EC070', 'MNDOT Elect. Comm GV', 'MN Department of Transportation', 'T79'),
('EC080', 'MNDOT Elect. Comm Rochester', 'MN Department of Transportation', 'T79'),
('EC084', 'MNDOT Elect. Comm Owatonna', 'MN Department of Transportation', 'T79'),
('EC090', 'MNDOT Elect. Comm Mankato', 'MN Department of Transportation', 'T79'),
('EC100', 'MNDOT Elect Comm Marshall', 'MN Department of Transportation', 'T79'),
('EC110', 'MNDOT Elect. Comm Oakdale', 'MN Department of Transportation', 'T79'),
('EC115', 'MNDOT Elect. Comm Waters Edge', 'MN Department of Transportation', 'T79'),
('EC120', 'MNDOT Elect. Comm Grand Rapids', 'MN Department of Transportation', 'T79'),
('EC130', 'MNDOT Elect. Comm Bemidji', 'MN Department of Transportation', 'T79'),
('EC160', 'MNDOT Elect. Comm Windom', 'MN Department of Transportation', 'T79'),
('ES000', 'MNDOT Electrical Services', 'MN Department of Transportation', 'T79'),
('ES001', 'MNDOT Electrical Services 1', 'MN Department of Transportation', 'T79'),
('G0201', 'Administration Department', 'MN Department of Administration', 'G02'),
('G0202', 'Mn Geospatial Info Office', 'MN Department of Administration', 'G02'),
('G0203', 'Minnesota Bookstore', 'MN Department of Administration', 'G02'),
('G0204', 'Central Mail', 'MN Department of Administration', 'G02'),
('G0205', 'Parking', 'MN Department of Administration', 'G02'),
('G0206', 'Materials Transfer', 'MN Department of Administration', 'G02'),
('G0207', 'Surplus Services', 'MN Department of Administration', 'G02'),
('G0208', 'Fleet Services', 'MN Department of Administration', 'G02'),
('G0209', 'Admin - Facilities Management', 'MN Department of Administration', 'G02'),
('G0210', 'Admin/State Procurement', 'MN Department of Administration', 'G02'),
('G0211', 'Admin - Real Estate & Constr', 'MN Department of Administration', 'G02'),
('G0212', 'Admin - Risk Management', 'MN Department of Administration', 'G02'),
('G0213', 'Risk Management - Workers Comp', 'MN Department of Administration', 'G02'),
('G0214', 'Financial Mgmt & Reporting', 'MN Department of Administration', 'G02'),
('G0215', 'Data Practices Office', 'MN Department of Administration', 'G02'),
('G0216', 'Admin FMR Smart', 'MN Department of Administration', 'G02'),
('G0217', 'Admin HR Smart', 'MN Department of Administration', 'G02'),
('G0218', 'Admin Demography', 'MN Department of Administration', 'G02'),
('G0219', 'State Hist Preservation Office', 'MN Department of Administration', 'G02'),
('G0220', 'Office of State Archaeology', 'MN Department of Administration', 'G02'),
('G0301', 'Lottery', 'Minnesota State Lottery', 'G03'),
('G0501', 'Racing Commission', 'Minnesota Racing Commission', 'G05'),
('G0601', 'Attorney General', 'Office of the MN Attorney General', 'G06'),
('G0901', 'Gambling Control Board', 'Minnesota Gambline Control Board', 'G09'),
('G1001', 'Minnesota Management & Budget', 'MN Management and Budget', 'G10'),
('G1002', 'SEGIP', 'MN Management and Budget', 'G10'),
('G1601', 'Admin Cap Project & Relocation', 'Admin CAP Project & Relocation', 'G16'),
('G1701', 'Human Rights Department', 'MN Department of Human Rights', 'G17'),
('G1901', 'Indian Affairs Council', 'Minnesota Indian Affairs Council', 'G19'),
('G3801', 'Investment Board', 'Minnesota State Board of Investment', 'G38'),
('G3901', 'Governors Office', 'Office of Governor', 'G39'),
('G4501', 'Mediation Services Department', 'Minnesota Bureau of Mediation Services', 'G45'),
('G4601', 'MN.IT', 'Minnesota IT Services', 'G46'),
('G5301', 'Secretary of State', 'Office of the Minnesota Secretary of State', 'G53'),
('G6101', 'Office of State Auditor', 'Office of Minnesota State Auditor', 'G61'),
('G6201', 'Minn State Retirement System', 'Minnesota State Retirement System', 'G62'),
('G6301', 'Public Employees Retire Assoc', 'Minnesota Public Employees Retirement Association', 'G63'),
('G6302', 'PERA - US BANK', 'Minnesota Public Employees Retirement Association', 'G63'),
('G6701', 'Revenue Department', 'MN Department of Revenue', 'G67'),
('G6901', 'Teachers Retirement Assoc', 'Teachers Retirement Association of Minnesota', 'G69'),
('G7001', 'MN Secure Choice Retirement Bd', 'The Minnesota Secure Choice Retirement Program', 'G70'),
('G8H01', 'MMB Higher Education', 'MN Management and Budget', 'G10'),
('G8S01', 'MMB Intergovernmental Aids', 'MN Management and Budget', 'G10'),
('G9001', 'Revenue Intergovt Payments', 'MN Management and Budget', 'G10'),
('G9201', 'Ombudsperson for Families', 'Minnesota Office of Ombudsperson for Families', 'G92'),
('G9301', 'Ombud American Indian Families', 'Minnesota Office of Ombudsperson for American Indian Families', 'G93'),
('G9601', 'Uniform Laws Commission', 'The Minnesota Uniform Laws Commission', 'G96'),
('G9J01', 'Campaign Finance Board', 'Minnesota Campaign Finance Board', 'G9J'),
('G9K01', 'Administrative Hearings', 'Minnesota Court of Administrative Hearings', 'G9K'),
('G9L01', 'Council for Minnesotans of Afr', 'Council for Minnesotans of African Heritage', 'G9L'),
('G9M01', 'Minnesota Council on Latino Af', 'Minnesota Council on Latino Affairs', 'G9M'),
('G9N01', 'Asian Pacific Council', 'Council on Asian Pacific Minnesotans', 'G9N'),
('G9P01', 'LGBTQIA2S+ Minnesotans Council', 'The Council on LGBTQIA2S+ Minnesotans', 'G9P'),
('G9Q01', 'MMB Debt Service', 'MN Management and Budget', 'G10'),
('G9R01', 'MMB Non-Operating', 'MN Management and Budget', 'G10'),
('G9T01', 'MMB Treasury Non Operating', 'MN Management and Budget', 'G10'),
('G9V01', 'Rare Disease Advisory Council', 'The Minnesota Rare Disease Advisory Council', 'G9V'),
('G9X01', 'Capitol Area Architect', 'Capitol Area Architectural and Planning Board', 'G9X'),
('G9Y01', 'MN State Council on Disability', 'Minnesota Council on Disability', 'G9Y'),
('GCA01', 'ACH Clearing', 'MN Department of Revenue', 'G67'),
('GF000', 'MNDOT Metro District GV', 'MN Department of Transportation', 'T79'),
('GF110', 'MNDOT Metro Dist. Cedar Fuel', 'MN Department of Transportation', 'T79'),
('GF111', 'MNDOT Metro Dist. GV Mech', 'MN Department of Transportation', 'T79'),
('GF129', 'MNDOT Metro Dist. Shak Fuel', 'MN Department of Transportation', 'T79'),
('GF130', 'MNDOT Metro Dist. Camden Fuel', 'MN Department of Transportation', 'T79'),
('GF131', 'MNDOT Metro Dist. GV Fuel', 'MN Department of Transportation', 'T79'),
('GF133', 'MNDOT Metro Dist. Jordan Fuel', 'MN Department of Transportation', 'T79'),
('GF140', 'MNDOT Metro Dist. Anoka Fuel', 'MN Department of Transportation', 'T79'),
('GF163', 'MNDOT Metro Dist. PLY Fuel', 'MN Department of Transportation', 'T79'),
('GF179', 'MNDOT Metro Dist. SLP Fuel', 'MN Department of Transportation', 'T79'),
('GF186', 'MNDOT Metro Dist. EP Fuel', 'MN Department of Transportation', 'T79'),
('GF187', 'MNDOT Metro Dist. MG Fuel', 'MN Department of Transportation', 'T79'),
('GF196', 'MNDOT Metro Dist. EP Fuel', 'MN Department of Transportation', 'T79'),
('GF222', 'MNDOT Metro Dist Chaska Mech', 'MN Department of Transportation', 'T79'),
('GF333', 'MNDOT Metro Dist. Camden TS', 'MN Department of Transportation', 'T79'),
('GF444', 'MNDOT Metro Dist. EP TS', 'MN Department of Transportation', 'T79'),
('GF555', 'MNDOT Metro Dist. Cedar Mech', 'MN Department of Transportation', 'T79'),
('GF665', 'MAPLE GROVE FIELD MECH TRUCK', 'MN Department of Transportation', 'T79'),
('GF666', 'MNDOT Metro Dist. MG TS', 'MN Department of Transportation', 'T79'),
('GF667', 'MNDOT Metro Dist GF Mech TR', 'MN Department of Transportation', 'T79'),
('GF777', 'MNDOT Metro Dist. PLY TS', 'MN Department of Transportation', 'T79'),
('GF888', 'MNDOT METRO DIST. SLP TS', 'MN Department of Transportation', 'T79'),
('GF910', 'MNDOT Metro Dist. Cedar TS', 'MN Department of Transportation', 'T79'),
('GF926', 'MNDOT Metro Dist Chaska Maint', 'MN Department of Transportation', 'T79'),
('GF929', 'MNDOT Metro Dist. Shak TS', 'MN Department of Transportation', 'T79'),
('GF930', 'MNDOT Metro Dist. Camden TS', 'MN Department of Transportation', 'T79'),
('GF931', 'MNDOT Metro Dist GV TS', 'MN Department of Transportation', 'T79'),
('GF933', 'MNDOT Metro Dist. Jordan TS', 'MN Department of Transportation', 'T79'),
('GF940', 'MNDOT Metro Dist. Anoka TS', 'MN Department of Transportation', 'T79'),
('GF963', 'MNDOT Metro Dist PLY TS', 'MN Department of Transportation', 'T79'),
('GF979', 'MNDOT Metro Dist. SLP TS', 'MN Department of Transportation', 'T79'),
('GF986', 'MNDOT Metro Dist. EP TS', 'MN Department of Transportation', 'T79'),
('GF987', 'MNDOT Metro Dist. MG TS', 'MN Department of Transportation', 'T79'),
('GF999', 'MNDOT Metro Dist. GV Sign', 'MN Department of Transportation', 'T79'),
('GPR01', 'Payroll Clearing', 'MN Management and Budget', 'G10'),
('H1201', 'Health Department', 'MN Department of Health', 'H12'),
('H5101', 'Direct Care and Treatment', 'MN Direct Care and Treatment', 'H51'),
('H5110', 'DCT Billing', 'MN Direct Care and Treatment', 'H51'),
('H5111', 'MSI Billing', 'MN Direct Care and Treatment', 'H51'),
('H5501', 'Human Services Department', 'MN Department of Human Services', 'H55'),
('H5502', 'Grants and Projects', 'MN Department of Human Services', 'H55'),
('H5503', 'HealthCare Recoveries', 'MN Department of Human Services', 'H55'),
('H5504', 'Other Counties and Tribes', 'MN Department of Human Services', 'H55'),
('H5505', 'Parent Fees', 'MN Department of Human Services', 'H55'),
('H5506', 'Parent Usage', 'MN Department of Human Services', 'H55'),
('H5507', 'Estate Claims', 'MN Department of Human Services', 'H55'),
('H5508', 'Licensing', 'MN Department of Human Services', 'H55'),
('H5509', 'DHS Other', 'MN Department of Human Services', 'H55'),
('H5510', 'SOS Business Office', 'MN Department of Human Services', 'H55'),
('H5511', 'MSOP Business Office', 'MN Department of Human Services', 'H55'),
('H5512', 'MAEPD', 'MN Department of Human Services', 'H55'),
('H5513', 'Alternative Care', 'MN Department of Human Services', 'H55'),
('H5514', 'MSHO', 'MN Department of Human Services', 'H55'),
('H5515', 'MDHO', 'MN Department of Human Services', 'H55'),
('H5516', 'Special Needs Basic Care', 'MN Department of Human Services', 'H55'),
('H5517', 'Nursing Home Surcharge', 'MN Department of Human Services', 'H55'),
('H5518', 'Hospital Surcharge', 'MN Department of Human Services', 'H55'),
('H5519', 'HMO Surcharge', 'MN Department of Human Services', 'H55'),
('H5520', 'ICFDD Surcharge', 'MN Department of Human Services', 'H55'),
('H5521', 'ECPN', 'MN Department of Human Services', 'H55'),
('H5522', 'SIRS', 'MN Department of Human Services', 'H55'),
('H5523', 'MinnesotaCare Operations', 'MN Department of Human Services', 'H55'),
('H5524', 'NSR', 'MN Department of Human Services', 'H55'),
('H5525', 'MinnesotaCare Overpayments', 'MN Department of Human Services', 'H55'),
('H5526', 'PROVIDER CREDIT BALANCES', 'MN Department of Human Services', 'H55'),
('H5599', 'DHS - DOR Collections', 'MN Department of Human Services', 'H55'),
('H5801', 'Children Youth & Families Dept', 'MN Department of Children, Youth, and Families', 'H58'),
('H6001', 'MN Insurance Marketplace', 'MNsure', 'H60'),
('H6002', 'MNsure', 'MNsure', 'H60'),
('H7501', 'Veterans Affairs Department', 'MN Department of Veterans Affairs', 'H75'),
('H7B01', 'Medical Practice Board', 'Minnesota Board of Medical Practice', 'H7B'),
('H7C01', 'Nursing Board', 'Minnesota Board of Nursing', 'H7C'),
('H7D01', 'Pharmacy Board', 'Minnesota Board of Pharmacy', 'H7D'),
('H7F01', 'Dentistry Board', 'Minnesota Board of Dentistry', 'H7F'),
('H7H01', 'Chiropractic Examiners Board', 'Minnesota Board of Chiropractic Examiners', 'H7H'),
('H7J01', 'Optometry Board', 'Minnesota Board of Optometry', 'H7J'),
('H7K01', 'Exec for LT Svcs & Supports Bd', 'Minnesota Board of Executives for Long-Term Services and Supports', 'H7K'),
('H7L01', 'Social Work Board', 'Minnesota Board of Social Work', 'H7L'),
('H7M01', 'Marriage and Family Therapy Bd', 'Minnesota Board of Marriage and Family Therapy', 'H7M'),
('H7Q01', 'Podiatric Medicine', 'Minnesota Board of Podiatric Medicine', 'H7Q'),
('H7R01', 'Veterinary Medicine Board', 'Minnesota Board of Veterinary Medicine', 'H7R'),
('H7S01', 'Emergency Medical Services Off', 'Minnesota Office of Emergency Medical Services', 'H7S'),
('H7U01', 'Dietetics & Nutrition Practice', 'Minnesota Board of Dietetics and Nutrition Practice', 'H7U'),
('H7V01', 'Psychology Board', 'Minnesota Board of Psychology', 'H7V'),
('H7W01', 'Physical Therapy Board', 'Minnesota Board of Physical Therapy', 'H7W'),
('H7X01', 'Behavioral Health & Therapy Bd', 'Minnesota Board of Behavioral Health and Therapy', 'H7X'),
('H7Y01', 'Occupational Therapy Pract Bd', 'Minnesota Board of Occupational Therapy Practice', 'H7Y'),
('H8A01', 'Foster Youth Ombudsperson', 'Minnesota Office of the Foster Youth Ombudsperson', 'H8A'),
('H8S01', 'Emergency Medical Services Off', 'MN Department of Human Services', 'H55'),
('H9G01', 'Ombudsman MH/DD', 'Minnesota Office of Ombudsman for Mental Health and Developmental Disabilities', 'H9G'),
('J3301', 'Trial Courts', 'Minnesota Judicial Branch - Trial Courts', 'J33'),
('J4001', 'STATE COMPETENCY ATTAINMENT BD', 'Minnesota Competency Attainment Board', 'J40'),
('J5001', 'State Guardian Ad Litem', 'Minnesota Guardian ad Litem Board', 'J50'),
('J5201', 'Public Defense Board', 'State of Minnesota Board of Public Defense', 'J52'),
('J5801', 'Court of Appeals', 'Minnesota Court of Appeals', 'J58'),
('J6101', 'Appellate Counsel & Trg Office', 'Office of Appellate Counsel and Training', 'J61'),
('J6301', 'State Board of Civil Legal Aid', 'State Board of Civil Legal Aid', 'J63'),
('J6501', 'Supreme Court', 'Minnesota Supreme Court', 'J65'),
('J6801', 'Tax Court', 'Minnesota Tax Court', 'J68'),
('J7001', 'Judicial Standards Board', 'Minnesota Board on Judicial Standards', 'J70'),
('L1001', 'Legislature Coordinating Comm', 'Minnesota Legislative Coordinating Commission', 'L10'),
('L1101', 'Senate', 'Minnesota Senate', 'L11'),
('L1201', 'House', 'Minnesota House of Representatives', 'L12'),
('L4901', 'Legislative Auditor', 'Minnesota Office of the Legislative Auditor', 'L49'),
('LAB00', 'MDH/MDA Lab', 'Minnesota Department of Administration Agriculture and Health Laboratory', 'G02'),
('MK000', 'MNDOT District 7 Mankato', 'MN Department of Transportation', 'T79'),
('MK415', 'MNDOT District 7 Blue Earth TS', 'MN Department of Transportation', 'T79'),
('MK416', 'MNDOT District 7 Wells TS', 'MN Department of Transportation', 'T79'),
('MK418', 'MNDOT District 7 St. Peter TS', 'MN Department of Transportation', 'T79'),
('MK421', 'MNDOT District 7 Waseca TS', 'MN Department of Transportation', 'T79'),
('MK423', 'MNDOT District 7 Mapleton TS', 'MN Department of Transportation', 'T79'),
('MK424', 'MNDOT District 7 Courtland TS', 'MN Department of Transportation', 'T79'),
('MK430', 'MNDOT District 7 LeSueur TS', 'MN Department of Transportation', 'T79'),
('MK437', 'MNDOT District 7 Montgomery TS', 'MN Department of Transportation', 'T79'),
('MK438', 'MNDOT District 7 Gaylord TS', 'MN Department of Transportation', 'T79'),
('MK492', 'MNDOT District 7 Green Isle TS', 'MN Department of Transportation', 'T79'),
('MK494', 'MNDOT District 7 Field Mech', 'MN Department of Transportation', 'T79'),
('MK700', 'MNDOT District 7 Mankato Yard', 'MN Department of Transportation', 'T79'),
('MK717', 'MNDOT District 7 Watervil Salt', 'MN Department of Transportation', 'T79'),
('MK718', 'MNDOT District 7 Alden Salt', 'MN Department of Transportation', 'T79'),
('MK997', 'MNDOT District 7 Mankato Brg', 'MN Department of Transportation', 'T79'),
('MK999', 'MNDOT Dist 7 Mankato Sign Shop', 'MN Department of Transportation', 'T79'),
('ML000', 'MNDOT District 8 Marshall', 'MN Department of Transportation', 'T79'),
('ML999', 'MNDOT District 8 Marshall Sign', 'MN Department of Transportation', 'T79'),
('MO000', 'MNDOT District 4 Morris', 'MN Department of Transportation', 'T79'),
('MO781', 'MNDOT District 4 Wheaton Pit', 'MN Department of Transportation', 'T79'),
('MO782', 'MNDOT District 4 Graceville Pi', 'MN Department of Transportation', 'T79'),
('MO783', 'MNDOT DISTRICT 4 BRUSHVALE PIT', 'MN Department of Transportation', 'T79'),
('MO802', 'MNDOT District 4 Appleton', 'MN Department of Transportation', 'T79'),
('MO806', 'MNDOT District 4 Wheaton', 'MN Department of Transportation', 'T79'),
('MO807', 'MNDOT District 4 Beardsley', 'MN Department of Transportation', 'T79'),
('MO808', 'MNDOT District 4 Glenwood', 'MN Department of Transportation', 'T79'),
('MO809', 'MNDOT District 4 Barrett Salt', 'MN Department of Transportation', 'T79'),
('MO816', 'MNDOT District 4 Evansville', 'MN Department of Transportation', 'T79'),
('MO818', 'MNDOT District 4 Alexanndria', 'MN Department of Transportation', 'T79'),
('MO819', 'MNDOT District 4 Ortonville', 'MN Department of Transportation', 'T79'),
('MO820', 'MNDOT District 4 Morris HQ', 'MN Department of Transportation', 'T79'),
('MO821', 'MNDOT District 4 Morris Cold', 'MN Department of Transportation', 'T79'),
('MO822', 'MNDOT District 4 Benson', 'MN Department of Transportation', 'T79'),
('MO900', 'MNDOT District 4 Morris Bldg', 'MN Department of Transportation', 'T79'),
('MO907', 'MNDOT District 4 Morris East', 'MN Department of Transportation', 'T79'),
('MO908', 'MNDOT District 4 Morris West', 'MN Department of Transportation', 'T79'),
('MO918', 'MNDOT District 4 Alexandria', 'MN Department of Transportation', 'T79'),
('MO999', 'MNDOT District 4 Sign Shop', 'MN Department of Transportation', 'T79'),
('OD000', 'MNDOT Metro Dist. Oakdale', 'MN Department of Transportation', 'T79'),
('OD111', 'MNDOT Metro Dist Maryland Mech', 'MN Department of Transportation', 'T79'),
('OD117', 'MNDOT Metro Dist Maplewood', 'MN Department of Transportation', 'T79'),
('OD118', 'MNDOT Metro Dist. AH TS', 'MN Department of Transportation', 'T79'),
('OD138', 'MNDOT Metro Dist Oak TS', 'MN Department of Transportation', 'T79'),
('OD139', 'MNDOT Metro Dist FL TS', 'MN Department of Transportation', 'T79'),
('OD140', 'MNDOT Metro Dist. NB TS', 'MN Department of Transportation', 'T79'),
('OD141', 'MNDOT Metro Dist. Lakeville TS', 'MN Department of Transportation', 'T79'),
('OD152', 'MNDOT Metro Dist. Mendota TS', 'MN Department of Transportation', 'T79'),
('OD153', 'MNDOT Metro Dist. Hastings TS', 'MN Department of Transportation', 'T79'),
('OD165', 'MNDOT Metro Dist. Maryland TS', 'MN Department of Transportation', 'T79'),
('OD222', 'MNDOT Metro Dist Hasting Mech', 'MN Department of Transportation', 'T79'),
('OD333', 'MNDOT Metro Dist FL Mech', 'MN Department of Transportation', 'T79'),
('OD444', 'MNDOT Metro Dist Oak Mech', 'MN Department of Transportation', 'T79'),
('OD445', 'MNDOT Metro Dist OD Mech TR', 'MN Department of Transportation', 'T79'),
('OD555', 'MNDOT Metro Dist. Hasting Mech', 'MN Department of Transportation', 'T79'),
('OD666', 'MNDOT Metro Dist. AH Mech', 'MN Department of Transportation', 'T79'),
('OD777', 'MNDOT Metro Mendota Mech', 'MN Department of Transportation', 'T79'),
('OD999', 'MNDOT Dist Oak Sign', 'MN Department of Transportation', 'T79'),
('OS000', 'MNDOT Sign Shop', 'MN Department of Transportation', 'T79'),
('OS001', 'MNDOT Sign Shop Finished Goods', 'MN Department of Transportation', 'T79'),
('OW000', 'MNDOT District 6 Owatonna', 'MN Department of Transportation', 'T79'),
('OW301', 'MNDOT District 6 Austin Stock', 'MN Department of Transportation', 'T79'),
('OW302', 'MNDOT District 6 AlbertLea SP', 'MN Department of Transportation', 'T79'),
('OW303', 'MNDOT District 6 Redwing Stock', 'MN Department of Transportation', 'T79'),
('OW305', 'MNDOT District 6 Owatonna Stoc', 'MN Department of Transportation', 'T79'),
('OW317', 'MNDOT District 6 Northfield', 'MN Department of Transportation', 'T79'),
('OW319', 'MNDOT District 6 Albert Lea', 'MN Department of Transportation', 'T79'),
('OW328', 'MNDOT District 6 Faribault', 'MN Department of Transportation', 'T79'),
('OW331', 'MNDOT District 6 Cannon Falls', 'MN Department of Transportation', 'T79'),
('OW339', 'MNDOT District 6 Zumbrota', 'MN Department of Transportation', 'T79'),
('OW349', 'MNDOT District 6 Austin', 'MN Department of Transportation', 'T79'),
('OW354', 'MNDOT District 6 Redwing', 'MN Department of Transportation', 'T79'),
('OW361', 'MNDOT District 6 Dodge Center', 'MN Department of Transportation', 'T79'),
('OW659', 'MNDOT DIST 6 BLOOMING PR SALT', 'MN Department of Transportation', 'T79'),
('OW662', 'MNDOT DIST 6 FARIBAULT SALT', 'MN Department of Transportation', 'T79'),
('OW663', 'MNDOT DIST 6 KASSON SALT', 'MN Department of Transportation', 'T79'),
('OW664', 'MN DOT DIST 6 LE ROY SALT SHED', 'MN Department of Transportation', 'T79'),
('OW999', 'MNDOT District 6 Sign Shop', 'MN Department of Transportation', 'T79'),
('P0101', 'Military Affairs Department', 'Minnesota Department of Military Affairs', 'P01'),
('P0701', 'Public Safety Department', 'Minnesota Department of Public Safety', 'P07'),
('P0702', 'Homeland Security', 'Minnesota Department of Public Safety - Homeland Security and Emergency Management', 'P07'),
('P0703', 'BCA', 'Minnesota Department of Public Safety - Bureau of Criminal Apprehension', 'P07'),
('P0704', 'Fire Marshal', 'Minnesota Department of Public Safety - State Fire Marshal', 'P07'),
('P0705', 'State Patrol', 'Minnesota Department of Public Safety - State Patrol', 'P07'),
('P0706', 'AGED', 'Minnesota Department of Public Safety - Alcohol and Gambling Enforcement', 'P07'),
('P0707', 'DVS', 'Minnesota Department of Public Safety - Driver & Vehicle Services', 'P07'),
('P0708', 'Pipeline Safety', 'Minnesota Department of Public Safety - Office of Pipeline Safety', 'P07'),
('P0801', 'Ombudsperson for Corrections', 'Minnesota Office of the Ombuds for Corrections', 'P08'),
('P7801', 'Corrections Department', 'Minnesota Department of Corrections', 'P78'),
('P7T01', 'Peace Officers Board (POST)', 'Minnesota Board of Peace Officer Standards and Training', 'P7T'),
('P8001', 'Cannabis Expungement Board', 'Minnesota Cannabis Expungement Board', 'P80'),
('P8201', 'Clemency Review Commission', 'Minnesota Clemency Review Commission', 'P82'),
('P9E01', 'Sentencing Guidelines Comm', 'Minnesota Sentencing Guidelines Commission', 'P9E'),
('R2801', 'Minn Conservation Corps', 'MN Department of Natural Resources', 'R29'),
('R2901', 'Natural Resources Department', 'MN Department of Natural Resources', 'R29'),
('R3201', 'Pollution Control Agency', 'Minnesota Pollution Control Agency', 'R32'),
('R9P01', 'Water and Soil Resources Board', 'Minnesota Board of Water and Soil Resources', 'R9P'),
('RO000', 'MNDOT District 6 Rochester', 'MN Department of Transportation', 'T79'),
('RO109', 'MNDOT Dist 6 Rochester Bridge', 'MN Department of Transportation', 'T79'),
('RO218', 'MNDOT District 6 Winona', 'MN Department of Transportation', 'T79'),
('RO219', 'MNDOT District 6 Winona Bridge', 'MN Department of Transportation', 'T79'),
('RO220', 'MNDOT District 6 Stewartville', 'MN Department of Transportation', 'T79'),
('RO229', 'MNDOT District 6 St. Charles', 'MN Department of Transportation', 'T79'),
('RO252', 'MNDOT District 6 Dresbach', 'MN Department of Transportation', 'T79'),
('RO270', 'MNDOT DIST 6 ROCHESTER MAINT', 'MN Department of Transportation', 'T79'),
('RO601', 'MN DOT DIST 6 RUSHFORD SALT SH', 'MN Department of Transportation', 'T79'),
('RO602', 'MNDOT District 6 Chatfield', 'MN Department of Transportation', 'T79'),
('RO603', 'MNDOT District 6 Caledonia', 'MN Department of Transportation', 'T79'),
('RO605', 'MNDOT District 6 La Cresent', 'MN Department of Transportation', 'T79'),
('RO606', 'MNDOT District 6 Houston', 'MN Department of Transportation', 'T79'),
('RO607', 'MN DOT DIST 6 PRESTON SALT SHE', 'MN Department of Transportation', 'T79'),
('RO609', 'MNDOT District 6 Spring Valley', 'MN Department of Transportation', 'T79'),
('RO611', 'MN DOT DIST 6 WABASHA SALT SHE', 'MN Department of Transportation', 'T79'),
('RO614', 'MN DOT DIST 6 WILSON SALT SHED', 'MN Department of Transportation', 'T79'),
('RO999', 'MNDOT District 6 Sign Shop', 'MN Department of Transportation', 'T79'),
('SC000', 'MNDOT District 3 St. Cloud', 'MN Department of Transportation', 'T79'),
('SC471', 'MNDOT DISTRICT 3 ISLE', 'MN Department of Transportation', 'T79'),
('SC707', 'MNDOT District 3 Paynesville', 'MN Department of Transportation', 'T79'),
('SC708', 'MNDOT District 3 Cambridge', 'MN Department of Transportation', 'T79'),
('SC713', 'MNDOT District 3 Mora', 'MN Department of Transportation', 'T79'),
('SC714', 'MNDOT District 3 Foley', 'MN Department of Transportation', 'T79'),
('SC715', 'CLEARWATER TRUCK STATION', 'MN Department of Transportation', 'T79'),
('SC740', 'MNDOT Distric 3 Albany', 'MN Department of Transportation', 'T79'),
('SC741', 'MNDOT Distric 3 Elk River', 'MN Department of Transportation', 'T79'),
('SC742', 'MNDOT District 3 Monticello', 'MN Department of Transportation', 'T79'),
('SC749', 'MNDOT District 3 Milaca', 'MN Department of Transportation', 'T79'),
('SC753', 'MNDOT District 3 Buffalo', 'MN Department of Transportation', 'T79'),
('SC772', 'MNDOT District 3 Sauk Centre', 'MN Department of Transportation', 'T79'),
('SC900', 'MNDOT Dist 3 St. Cloud Maint', 'MN Department of Transportation', 'T79'),
('SC999', 'MNDOT District 3 Sign Shop', 'MN Department of Transportation', 'T79'),
('SSC00', 'MDH Support Services Center', 'MN Department of Human Services', 'H55'),
('T7901', 'Transportation Department', 'MN Department of Transportation', 'T79'),
('T7902', 'Transportation Restitution', 'MN Department of Transportation', 'T79'),
('T7903', 'Transportation Misc Interest', 'MN Department of Transportation', 'T79'),
('T7904', 'Transportation Joint Projects', 'MN Department of Transportation', 'T79'),
('T79FA', 'Transportation Project Billing', 'MN Department of Transportation', 'T79'),
('T9B01', 'Metropolitan Council/Transport', 'The Metropolitan Council', 'T9B'),
('VA000', 'MNDOT District 1 Virginia', 'MN Department of Transportation', 'T79'),
('VA002', 'HIBBING WEST FIELD MECHANIC', 'MN Department of Transportation', 'T79'),
('VA012', 'MNDOT District 1 Cook', 'MN Department of Transportation', 'T79'),
('VA022', 'MNDOT District 1 Ely', 'MN Department of Transportation', 'T79'),
('VA023', 'MNDOT District 1 VA Salt Sand', 'MN Department of Transportation', 'T79'),
('VA027', 'MNDOT District 1 VA Guardrail', 'MN Department of Transportation', 'T79'),
('VA033', 'MNDOT District 1 Little Fork', 'MN Department of Transportation', 'T79'),
('VA040', 'MNDOT District 1 Intl Falls', 'MN Department of Transportation', 'T79'),
('VA055', 'MNDOT District 1 Hibbing', 'MN Department of Transportation', 'T79'),
('VA056', 'MNDOT District 1 Deer Lake', 'MN Department of Transportation', 'T79'),
('VA100', 'MNDOT District 1 Biwabik', 'MN Department of Transportation', 'T79'),
('VA120', 'MNDOT District 1 Melrude', 'MN Department of Transportation', 'T79'),
('VA130', 'MNDOT District 1 Tower', 'MN Department of Transportation', 'T79'),
('VA300', 'MNDOT District 1 Big Falls', 'MN Department of Transportation', 'T79'),
('VA310', 'MNDOT District 1 Buck Lake', 'MN Department of Transportation', 'T79'),
('VA320', 'MNDOT District 1 Kinmount', 'MN Department of Transportation', 'T79'),
('VA500', 'MN DOT DIST 1 TOGO PIT', 'MN Department of Transportation', 'T79'),
('VA700', 'MNDOT District 1 Angora', 'MN Department of Transportation', 'T79'),
('VA999', 'MNDOT District 1 Sign Shop', 'MN Department of Transportation', 'T79'),
('WE000', 'MNDOT METRO DIST ROSEVILLE IN', 'MN Department of Transportation', 'T79'),
('WI000', 'MNDOT District 7 Windom', 'MN Department of Transportation', 'T79'),
('WI444', 'MNDOT District 7 Windom Stock', 'MN Department of Transportation', 'T79'),
('WI555', 'MNDOT District 7 Windom Const', 'MN Department of Transportation', 'T79'),
('WI609', 'MNDIT District 7 Luverne', 'MN Department of Transportation', 'T79'),
('WI613', 'MNDOT District 7 Worthington', 'MN Department of Transportation', 'T79'),
('WI614', 'MNDOT District 7 Windom Yard', 'MN Department of Transportation', 'T79'),
('WI616', 'MNDOT District 7 Jackson', 'MN Department of Transportation', 'T79'),
('WI620', 'MNDOT District 7 Fairmont', 'MN Department of Transportation', 'T79'),
('WI627', 'MNDOT District 7 Sleepy Eye', 'MN Department of Transportation', 'T79'),
('WI629', 'MNDOT District 7 Adrian', 'MN Department of Transportation', 'T79'),
('WI632', 'MNDOT District 7 St. James', 'MN Department of Transportation', 'T79'),
('WI694', 'MNDOT District 7 Sherburn', 'MN Department of Transportation', 'T79'),
('WI695', 'MNDOT District 7 Madelia', 'MN Department of Transportation', 'T79'),
('WI697', 'MNDOT District 7 Windom Bridge', 'MN Department of Transportation', 'T79'),
('WI997', 'MNDOT District 7 Windom Bridge', 'MN Department of Transportation', 'T79'),
('WI999', 'MNDOT Dist 7 Windom Sign Shop', 'MN Department of Transportation', 'T79'),
('WL000', 'MNDOT District 8 Willmar', 'MN Department of Transportation', 'T79'),
('WL023', 'MNDOT District 8 Willmar Road', 'MN Department of Transportation', 'T79'),
('WL521', 'MNDOT District 8 Madison Fuel', 'MN Department of Transportation', 'T79'),
('WL523', 'MNDOT District 8 Willmar Fuel', 'MN Department of Transportation', 'T79'),
('WL703', 'MNDOT District 8 Glencoe SP', 'MN Department of Transportation', 'T79'),
('WL704', 'MNDOT Dist 8 Montevideo SP', 'MN Department of Transportation', 'T79'),
('WL705', 'MNDOT District 8 Litchfield SP', 'MN Department of Transportation', 'T79'),
('WL706', 'MNDOT District 8 Hutchinson SP', 'MN Department of Transportation', 'T79'),
('WL723', 'MNDOT District 8 Willmar Yard', 'MN Department of Transportation', 'T79'),
('WL802', 'MNDOT District 8 Pipestone SP', 'MN Department of Transportation', 'T79'),
('WL807', 'MNDOT District 8 Tracy SP', 'MN Department of Transportation', 'T79'),
('WL814', 'MNDOT District 8 Ivanhoe SP', 'MN Department of Transportation', 'T79'),
('WL815', 'MNDOT District 8 Olivia SP', 'MN Department of Transportation', 'T79'),
('WL821', 'MNDOT District 8 Madison SP', 'MN Department of Transportation', 'T79'),
('WL823', 'MNDOT District 8 Marshall SP', 'MN Department of Transportation', 'T79'),
('WL834', 'MNDOT District 8 Slayton SP', 'MN Department of Transportation', 'T79'),
('WL836', 'MNDOT Dist 8 Redwood Falls SP', 'MN Department of Transportation', 'T79'),
('WL839', 'MNDOT Dist 8 Granite Falls SP', 'MN Department of Transportation', 'T79'),
('WL999', 'MNDOT District 8 Willmar Sign', 'MN Department of Transportation', 'T79');